### ISSUE TITLE
Some browsers don't support arrow functions

### ISSUE THREAD

**Issue by glukki** [screeps/tutorial-scripts#1]
These lines lead to error `Unexpected token '>'` in Safari
https://github.com/screeps/tutorial-scripts/blob/master/section3/role.harvester.js#L13
https://github.com/screeps/tutorial-scripts/blob/master/section4/main.js#L12
https://github.com/screeps/tutorial-scripts/blob/master/section4/role.harvester.js#L13
https://github.com/screeps/tutorial-scripts/blob/master/section5/main.js#L10
https://github.com/screeps/tutorial-scripts/blob/master/section5/role.harvester.js#L13

**Comment by artch** [comment]
Thank you for participating.

The Steam version of the game is packed with Chromium. For the web version we recommend using Chrome. And arrow functions are already supported in Safari 10, so this should not be a problem very soon. Arrow functions feature is cleaner syntax which we would like to keep in our tutorial.
