### ISSUE TITLE
Suggestion: Add console commands to readme

### ISSUE THREAD

**Issue by eslachance** [screeps/tutorial-scripts#3]
It would be very useful to have a reminder of the console commands used during tutorials. For example the command to build the turret.

**Comment by artch** [comment]
Do you mean in README.md in this reposistory?

**Comment by eslachance** [comment]
Yes. Actually having I believe it's possible to have a readme in each folder with more details about that folder, so having `https://github.com/screeps/tutorial-scripts/tree/master/section1/README.md` for example, with the commands used in the tutorial 1 (spawning a creep!) would be possible.

**Comment by artch** [comment]
This makes sense. I think we'll add all tutorial steps with their text messages and code snippets here later.

**Comment by gerty** [comment]
*bump*
(this would be very useful for beginners)

**Comment by cp4r3z** [comment]
I had the same thought. See PR #6.
