### ISSUE TITLE
I needed to rename role.Harvester to role.harvester

### ISSUE THREAD

**Issue by shawn-sher** [screeps/tutorial-scripts#5]
The tutorial said I needed to create a module called role.Harvester, but did not recognize what I had created until I noticed that the script name here was role.harvester.js. Once I renamed it, the tutorial saw it and continued.

**Comment by artch** [comment]
Sorry, I can't seem to understand what is your problem exactly?

**Comment by shawn-sher** [comment]
It was my own fault. I read the instructions incorrectly.
